image:
  repository: jordaan0/caesar_openmpi
  tag: latest

networkPolicy:
  enabled: false

sshGateway:
  enabled: false
  nodePort: 30220

mpiMaster:
  autoUpdateHostfile:
    enabled: true
  nodeSelector: {}
  tolerations: []
  affinity: {}

mpiWorkers:
  num: 3
  nodeSelector: {}
  tolerations: []
  affinity: {}
