{{ if and .Values.mpiWorkers.customScheduling.enabled .Values.mpiWorkers.customScheduling.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-pdb
spec:
  minAvailable: {{ .Values.mpiWorkers.num }}
  selector:
    matchLabels:
      app: {{ template "..name" . }}
      chart: {{ template "..chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: worker
---
{{ end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: worker
spec:
  selector:
    matchLabels:
      app: {{ template "..name" . }}
      chart: {{ template "..chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: worker
  serviceName: {{ .Release.Name }}
  podManagementPolicy: {{.Values.mpiWorkers.podManagementPolicy}}
  replicas: {{.Values.mpiWorkers.num}}
  template:
    metadata:
      labels:
        app: {{ template "..name" . }}
        chart: {{ template "..chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: worker
    spec:
{{- if .Values.mpiWorkers.customScheduling.enabled }}
      schedulerName: {{.Values.mpiWorkers.customScheduling.schedulerName}}
{{- end }}
      securityContext:
{{ toYaml .Values.mpiWorkers.securityContext | indent 8 }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 6 }}
{{- end }}
      volumes:
      - name: kube-openmpi-ssh-key
        secret:
          secretName: {{ .Release.Name }}-ssh-key
          defaultMode: 256
      - name: kube-openmpi-utils
        configMap:
          name: {{ .Release.Name }}-assets
          items:
          - key: gen_hostfile.sh
            path: gen_hostfile.sh
            mode: 365
      {{- range .Values.appCodesToSync }}
      - name: kube-openmpi-sync-{{ .name }}
        emptyDir: {}
        {{- if .gitSecretName }}
      - name: kube-openmpi-sync-{{ .name }}-secret
        secret:
          secretName: {{ .gitSecretName }}
          defaultMode: 256
        {{- end }}
      {{- end }}
{{ if .Values.mpiWorkers.volumes }}
{{ toYaml .Values.mpiWorkers.volumes | indent  6 }}
{{ end }}
      initContainers:
      {{- $root := . -}}
      {{- range .Values.appCodesToSync }}
      - name: {{ .name }}-fetch
        image: {{ $root.Values.gitSyncImage.repository }}:{{ $root.Values.gitSyncImage.tag }}
        imagePullPolicy: {{ $root.Values.gitSyncImage.pullPolicy }}
        env:
        - name: GIT_SYNC_REPO
          value: {{ .gitRepo }}
        - name: GIT_SYNC_BRANCH
          value: {{ .gitBranch }}
        - name: GIT_SYNC_DEST
          value: {{ .name }}
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_WAIT
          value: {{ .fetchWaitSecond | default "0" | quote }}
        {{- if .gitSecretName }}
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_KNOWN_HOSTS
          value: "false"
        {{- end }}
        volumeMounts:
        - name: kube-openmpi-sync-{{ .name }}
          mountPath: /git
        {{- if .gitSecretName }}
        - name: kube-openmpi-sync-{{ .name }}-secret
          mountPath: /etc/git-secret
        securityContext:
          runAsUser: 0
        {{- end }}
      {{- end }}
      containers:
      - name: mpi-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 2022
          containerPort: 8080
        volumeMounts:
        - name: kube-openmpi-ssh-key
          mountPath: /ssh-key/openmpi
        - name: kube-openmpi-utils
          mountPath: /kube-openmpi/utils
        {{- range .Values.appCodesToSync }}
        - name: kube-openmpi-sync-{{ .name }}
          mountPath: {{ .mountPath }}
          {{ if .subPath }}subPath: {{.subPath}} {{ end }}
        {{- end }}
{{ if .Values.mpiWorkers.volumeMounts }}
{{ toYaml .Values.mpiWorkers.volumeMounts | indent 8 }}
{{ end }}
        resources:
{{ toYaml .Values.mpiWorkers.resources | indent 10 }}
      {{- with .Values.mpiWorkers.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.mpiWorkers.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.mpiWorkers.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
