# using https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#creating-the-redis-master-service

apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: {{.Values.redisMaster.spec.replicas}}
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: {{.Values.redisMaster.spec.template.spec.containers.image}}  # or just image: redis
        resources: 
          requests:
            cpu: {{.Values.redisMaster.spec.template.spec.containers.resources.requests.cpu}}
            memory: {{.Values.redisMaster.spec.template.spec.containers.resources.requests.memory}}
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: {{.Values.redisSlave.spec.replicas}}
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: {{.Values.redisSlave.spec.template.spec.containers.image}}
        resources:
          requests:
            cpu: {{.Values.redisSlave.spec.template.spec.containers.resources.requests.cpu}}
            memory: {{.Values.redisSlave.spec.template.spec.containers.resources.requests.memory}}
        env:
        - name: GET_HOSTS_FROM
          value: {{.Values.redisSlave.spec.template.spec.containers.env.value}}
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379